### Copied verbatim from Big Bang customer template:
### https://repo1.dso.mil/big-bang/customers/template/-/blob/main/gitRepo/dev/bigbang.yaml?ref_type=heads.
### Presented here only for ease of reading in context with other files. No additional documentation added.

apiVersion: v1
kind: Namespace
metadata:
  name: bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  url: <YOUR_GIT_REPO_URL>
  ref:
    branch: master
  secretRef:
    name: private-git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./dev
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg

